# Generated by Django 3.1.1 on 2021-02-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-score']},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='api_organiz_name_d3d16b_idx'),
        ),
    ]
