name: application run tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./vough_backend

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test with Django
      run: |
        pytest -v . --cov api/
      working-directory: ${{env.working-directory}}